server:
#  ssl:
#    key-store: 5459475_bbxc.xyz.pfx
#    key-store-password: kIj6H657
#    key-store-type: PKCS12
#    enabled: true
  port: 8899 #项目启动访问端口
spring:
  application:
    name: goods
  datasource: #连接数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用域名进行连接
    url: jdbc:mysql://bbxc.xyz:3306/baoxiuapp?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: cjw1765152390
    hikari:
      minimum-idle: 3
      maximum-pool-size: 100
      max-lifetime: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart: #文件上传配置
      max-file-size: 20MB
      max-request-size: 50MB
projectName: estate-bg-manage